#!/usr/bin/env python3
"""Convert DermoAI ConvNeXt-Base PyTorch → TFLite.

Approach: torch dynamo export → ONNX → tensorflow direct conversion.
StochasticDepth disabled during trace to avoid control-flow ops.
"""
import os, sys, shutil
import numpy as np
import torch
import torch.nn as nn
from torchvision.models import convnext_base

# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------
class SkinCancerModel(nn.Module):
    def __init__(self, num_classes=12):
        super().__init__()
        self.backbone = convnext_base(weights=None)
        in_features = self.backbone.classifier[2].in_features
        self.backbone.classifier[2] = nn.Sequential(
            nn.Dropout(p=0.4),
            nn.Linear(in_features, 512),
            nn.GELU(),
            nn.Dropout(p=0.2),
            nn.Linear(512, num_classes),
        )

    def load_state_dict(self, state_dict, strict=True):
        has_seq = any(k.startswith("backbone.classifier.2.1.") for k in state_dict.keys())
        current_is_seq = isinstance(self.backbone.classifier[2], nn.Sequential)
        if has_seq != current_is_seq:
            ifeats = (self.backbone.classifier[2][1].in_features if current_is_seq
                      else self.backbone.classifier[2].in_features)
            ncls = (self.backbone.classifier[2][4].out_features if current_is_seq
                    else self.backbone.classifier[2].out_features)
            if has_seq:
                self.backbone.classifier[2] = nn.Sequential(
                    nn.Dropout(p=0.4), nn.Linear(ifeats, 512),
                    nn.GELU(), nn.Dropout(p=0.2), nn.Linear(512, ncls))
            else:
                self.backbone.classifier[2] = nn.Linear(ifeats, ncls)
        return super().load_state_dict(state_dict, strict=False)

    def forward(self, x):
        return self.backbone(x)


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PROJ = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CKPT = os.path.join(PROJ, "tools", "ml", "source", "ce_ls_best.pth")
TFLITE = os.path.join(PROJ, "app", "src", "main", "assets", "ml", "skin_model.tflite")


def main():
    device = torch.device("cpu")
    print(f"Loading {CKPT}…")
    model = SkinCancerModel(num_classes=12)
    ck = torch.load(CKPT, map_location=device, weights_only=False)
    sd = ck.get("model_state_dict", ck.get("model", ck))
    model.load_state_dict(sd)
    model.to(device)
    model.eval()

    # Eval mode already disables dropout and stochastic depth
    dummy = torch.randn(1, 3, 224, 224, device=device)

    # --- torch dynamo export → ONNX ---
    print("Exporting ONNX via torch dynamo…")
    import io
    onnx_bytes = io.BytesIO()
    torch.onnx.export(
        model, dummy, onnx_bytes,
        input_names=["input"], output_names=["output"],
        dynamic_axes={"input": {0: "batch"}, "output": {0: "batch"}},
        opset_version=17,
        dynamo=False,
    )
    onnx_bytes.seek(0)
    print(f"ONNX exported ({len(onnx_bytes.getvalue())/1e6:.1f} MB)")

    # --- ONNX → TensorFlow SavedModel via onnx2tf with numpy patch ---
    print("Converting ONNX → TensorFlow SavedModel via onnx2tf…")

    # Patch numpy to allow pickle for onnx2tf's test data
    import numpy
    _orig_np_load = numpy.load
    numpy.load = lambda *a, **k: _orig_np_load(*a, allow_pickle=True, **k)

    # Write ONNX to temp file for onnx2tf
    tmp_onnx = os.path.join(PROJ, "tools", "ml", "_tmp_conv.onnx")
    with open(tmp_onnx, "wb") as f:
        f.write(onnx_bytes.getvalue())

    tf_tmp = os.path.join(PROJ, "tools", "ml", "tflite_tmp")
    shutil.rmtree(tf_tmp, ignore_errors=True)

    from onnx2tf import convert as onnx2tf_convert
    onnx2tf_convert(
        input_onnx_file_path=tmp_onnx,
        output_folder_path=tf_tmp,
        output_signaturedefs=True,
        output_on_the_fly=True,
        non_verbose=True,
    )

    # Find generated .tflite
    import tensorflow as tf
    tflite_files = []
    for root, _, files in os.walk(tf_tmp):
        for f in files:
            if f.endswith(".tflite"):
                tflite_files.append(os.path.join(root, f))
    if not tflite_files:
        print("ERROR: No .tflite generated by onnx2tf")
        sys.exit(1)

    tflite_file = max(tflite_files, key=os.path.getsize)
    os.makedirs(os.path.dirname(TFLITE), exist_ok=True)
    shutil.copy(tflite_file, TFLITE)
    print(f"TFLite saved: {TFLITE} ({os.path.getsize(TFLITE)/1e6:.1f} MB)")

    # --- Smoke test ---
    tmp_onnx_for_test = os.path.join(PROJ, "tools", "ml", "_tmp_test.onnx")
    with open(tmp_onnx_for_test, "wb") as f:
        f.write(onnx_bytes.getvalue())

    import onnxruntime as ort
    sess = ort.InferenceSession(tmp_onnx_for_test, providers=["CPUExecutionProvider"])
    onnx_logits = sess.run(None, {"input": dummy.numpy()})[0]

    interp = tf.lite.Interpreter(model_path=TFLITE)
    interp.allocate_tensors()
    i_d = interp.get_input_details()
    o_d = interp.get_output_details()
    dummy_np = dummy.numpy()
    if list(i_d[0]["shape"]) == [1, 224, 224, 3]:
        dummy_np = np.transpose(dummy_np, (0, 2, 3, 1))
    interp.set_tensor(i_d[0]["index"], dummy_np.astype(np.float32))
    interp.invoke()
    tflite_logits = interp.get_tensor(o_d[0]["index"])

    def softmax(x):
        e = np.exp(x - x.max(axis=-1, keepdims=True))
        return e / e.sum(axis=-1, keepdims=True)

    diff = np.max(np.abs(softmax(onnx_logits) - softmax(tflite_logits)))
    print(f"\nMax softmax diff: {diff:.6f}  {'PASS' if diff < 0.02 else 'WARN'}")
    print(f"Top class: ONNX={np.argmax(onnx_logits[0])} TFLite={np.argmax(tflite_logits[0])}")
    print(f"\nDone! TFLite ready at: {TFLITE}")

    # Cleanup
    for p in [tmp_onnx, tmp_onnx_for_test]:
        try: os.remove(p)
        except: pass
    shutil.rmtree(tf_tmp, ignore_errors=True)


if __name__ == "__main__":
    main()
